dist:   trusty
sudo:   required

langauge:   cpp

os:
    - linux

compiler: g++

install: export CXX="g++-5"
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

before_install: sudo apt-get update -qq

script:
    - mkdir test_generator/test_data
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release .. 
    - make -j4
    - cd bin/
    - ./checker 
    - ./main 10
    - ./test_generator 
