dist:   trusty
sudo:   required

langauge:   cpp

os:
    - linux

compiler:
    - g++
install: export CXX="g++-5"
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release .. 
    - make -j4
    - ./checker 
    - ./main
    - ./test_generator 
